SUPABASE_URL = "https://kqthgqohlbtpphbgckth.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxdGhncW9obGJ0cHBoYmdja3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjI1NjIsImV4cCI6MjA2NzE5ODU2Mn0.YFnyLEaW3W-o3Pt3Bl8Meve7awrRasyAzQQMvy7zKao"
OPENAI_API_KEY = "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"
