SUPABASE_URL = "https://kqthgqohlbtpphbgckth.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxdGhncW9obGJ0cHBoYmdja3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjI1NjIsImV4cCI6MjA2NzE5ODU2Mn0.YFnyLEaW3W-o3Pt3Bl8Meve7awrRasyAzQQMvy7zKao"
OPENAI_API_KEY = "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"
